### Get Event
GET {{host}}/event/2023caph/practiceMatches
Accept: application/json
###

### Get matches team
GET {{host}}/event/2023utwv/team/4499/matches
Accept: application/json
###
### Get matches team
GET {{host}}/event/2023utwv/team/4499/matches
Accept: application/json
###

### Get matches team
GET {{host}}/event/2023utwv/matches/flat
Accept: application/json
###

### Get matches team
GET {{host}}/event/2023cokc/tbaTeams
Accept: application/json
###

### Get autos team
GET {{host}}/event/2023utwv/team/4499/autos
Accept: application/json
###

### Get matches team
GET {{host}}/event/2023utwv/team/4499/matches
Accept: application/json
###



### Patch Event
PATCH {{host}}/event/2023cokc/setMatches
Accept: application/json
###
### Patch Event
PATCH localhost:3001/2023/event/2023cokc/setMatches
Accept: application/json
###


### Get Events
GET {{host}}/2023/events
Accept: application/json
###

### Post Event
POST {{host}}/event
Content-Type: application/json

{
  "_id": "2023cokc"
}
###
GET {{host}}/event/2022code/match/qm48/team/frc5493


### Post Match
POST {{host}}/event/2022code/match/qm48/team
Content-Type: application/json

{
  "_id": "frc5493",
  "auto": {
    "startingPosition": {
      "x": 2.22321,
      "y": 1.3921
    },
    "mobility": true,
    "chargingStation": "DEFAULT",
    "path": [
      {
        "action": "PLACE",
        "object": "CONE",
        "placeHeight": "MIDDLE",
        "col": 2
      },
      {
        "action": "PICK",
        "object": "CONE",
        "position": 0
      },
      {
        "Action": "PLACE",
        "Object": "CONE",
        "placeHeight": "TOP",
        "col": 2
      }
    ]
  },
  "cycles": [
    {
      "object": "CONE",
      "pickupLocation": "DOUBLE_SUBSTATION_CHUTE",
      "placeHeight": "MIDDLE",
      "time": 10
    },
    {
      "object": "CUBE",
      "pickupLocation": "GROUND",
      "placeHeight": "TOP",
      "time": 7
    }
  ],
  "endGame": "DOCKED"
}

