#### Get Event
#GET http://localhost:3001/2023/event/2022code
#Accept: application/json
###
#### Get Event
#PATCH http://localhost:5000/2023/event/2022code/updateMatches
#Accept: application/json
####
#
#
#### Get Events
#GET http://localhost:5000/2023/events
#Accept: application/json
####
#
#### Post Event
#POST http://localhost:5000/2023/event
#Content-Type: application/json
#
#{
#  "_id": "2022code"
#}

### Post Match    2022code_qm7
POST http://localhost:3001/2023/event/2022code/match/qm11/putTeamScout
Content-Type: application/json

{
  "_id": "frc1339",
  "auto": {
    "startingPosition": {
      "x": 2.22321,
      "y": 1.3921
    },
    "mobility": true,
    "chargingStation": false,
    "path": []
  },
  "cycles": [],
  "endGame": true
}

